# Generated by Django 4.0.5 on 2022-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
