# Generated by Django 4.0.5 on 2022-06-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_show_end_time_alter_show_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show_seat',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.booking'),
        ),
    ]
