# Generated by Django 4.0.5 on 2022-06-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_show_seat_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='amount',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
